site_url: https://covid-19.hbs.hu

backend:
  name: git-gateway
#  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port for local git update
local_backend: true

# publish_mode: editorial_workflow # Allows you to save drafts before publishing them

media_folder: static/uploads # Media files will be stored in the repo under static/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /uploads

# nc-root: If Netlify CMS finds an element with this ID during initialization, it will mount within that element instead of creating its own.

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

i18n:
  structure: multiple_files
  locales: [hu, en, de] 
# , de, fr, es

collections:

  - name: index
    label: Pages
    label_singular: Page
    folder: content/pages/index
    delete: false
    create: true
    i18n: true
    identifier_field: menutitle
    #filter: {field: "type", value: "index"}
    summary: "{{menutitle}}"
    slug: "{{type}}"
    fields:
      - label: Type
        name: type
        widget: string
        default: index
        i18n: duplicate
      - label: URL alias
        name: slug
        widget: string
        i18n: true
      - label: Pinned (menu)
        name: pin
        i18n: true
        required: false
        widget: boolean
      - label: Fallback language
        name: fallback
        i18n: true
        required: false
        widget: select
        options:
          - { label: "Magyar", value: "hu" }
          - { label: "English", value: "en" }
          - { label: "Deutsch", value: "de" }
          - { label: "Fraçais", value: "fr" }
          - { label: "Español", value: "es" }
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Meta keywords
        name: keywords
        widget: string
        required: false
        i18n: true
      - label: Meta description
        name: description
        widget: string
        required: false
        i18n: true
      - label: Menutitle (short)
        name: menutitle
        widget: string
        i18n: true
      - label: Hero Image
        name: hero
        widget: image
        i18n: true
        required: false
      - label: Intro
        name: intro
        widget: object
        required: false
        i18n: true
        fields:
          - label: Intro highlight
            name: highlight
            widget: string
            required: false
            i18n: true
          - label: Intro images
            label_singular: Intro image
            name: images
            widget: list
            i18n: true
            fields: 
              - { label: 'Image', name: 'src', widget: 'image', i18n: true }
              - { label: 'Alt text', name: 'alt', widget: 'string', i18n: true }
              - { label: 'Caption', name: 'text', widget: 'markdown', required: false, i18n: true }
              - { label: 'Link', name: 'link', widget: 'string', required: false, i18n: true }
              - { label: 'CTA', name: 'cta', widget: 'string', required: false, i18n: true }
          - label: Intro text
            name: text
            widget: markdown
            required: false
            i18n: true
      - label: Info
        name: info
        widget: object
        required: false
        i18n: true
        fields:
          - label: Info images
            label_singular: Info image
            name: images
            widget: list
            i18n: true
            fields: 
              - { label: 'Image', name: 'src', widget: 'image', i18n: true }
              - { label: 'Alt text', name: 'alt', widget: 'string', i18n: true }
              - { label: 'Caption', name: 'text', widget: 'markdown', required: false, i18n: true }
          - label: Info text
            name: text
            widget: markdown
            required: false
            i18n: true
      - label: References
        name: references
        widget: object
        required: false
        i18n: true
        fields:
          - label: References text
            name: text
            widget: markdown
            required: false
            i18n: true
          - label: Reference links
            label_singular: Reference link
            name: links
            widget: list
            i18n: true
            fields: 
              - { label: 'Link URL', name: 'url', widget: 'string', i18n: true }
              - { label: 'Link text', name: 'text', widget: 'string', i18n: true }
      - label: Cards
        label_singular: Card
        name: cards
        widget: list
        required: false
        i18n: true
        fields:
          - label: Card text
            name: text
            widget: markdown
            i18n: true
          - label: Card link
            name: link
            widget: string
            i18n: true
          - label: Card image
            name: src
            widget: image
            i18n: true
      - label: Documents
        label_singular: Document
        name: documents
        widget: object
        required: false
        i18n: true
        fields:
          - label: References text
            name: text
            widget: markdown
            required: false
            i18n: true
          - label: Reference links
            label_singular: Reference link
            name: links
            widget: list
            i18n: true
            fields: 
              - label: Document text
                name: text
                widget: string
                i18n: true
              - label: Document link
                name: file
                widget: file
                i18n: true
              - label: Document image
                name: src
                widget: image
                i18n: true
      - label: Article blocks
        label_singular: Block
        name: articles
        widget: list
        i18n: true
        fields: 
          - label: Title
            name: title
            widget: string
            required: false
            i18n: true
          - label: Subtitle
            name: subtitle
            widget: string
            required: false
            i18n: true
          - label: Article content
            name: text
            widget: markdown
            i18n: true
      - {label: "HTML", name: "body", widget: "markdown", i18n: true, required: false}

  - name: qa
    label: Q&As
    label_singular: Q&A
    filter: {field: "type.hu", value: "faq"}
    i18n: true
    create: true
    #identifier_field: slug
    folder: "content/pages/qa"
    slug: "{{type}}"
    fields:
      - label: Type
        name: type
        default: "faq"
        i18n: duplicate
        widget: string
        #options:
        #  - { label: "FAQ", value: "faq" }
        #  - { label: "Myths", value: "myths" }
        #  - { label: "Business", value: "business" }
        #  - { label: "Private", value: "private" }
      - label: URL alias (slug)
        name: slug
        i18n: true
        widget: string
      - label: Pinned
        name: pin
        i18n: true
        required: false
        widget: boolean
      - label: Title
        name: title
        i18n: true
        widget: string
      - label: Meta keywords
        name: keywords
        widget: string
        required: false
        i18n: true
      - label: Meta description
        name: description
        widget: string
        required: false
        i18n: true
      - label: Subtitle
        name: subtitle
        required: false
        i18n: true
        widget: string
      - label: Menutitle (short)
        name: menutitle
        required: false
        i18n: true
        widget: string
      - label: Intro
        name: intro
        widget: object
        required: false
        i18n: true
        fields:
          - label: Intro highlight
            name: highlight
            widget: string
            required: false
            i18n: true
          - label: Intro images
            label_singular: Intro image
            name: images
            widget: list
            i18n: true
            fields: 
              - { label: 'Image', name: 'src', widget: 'image', i18n: true }
              - { label: 'Alt text', name: 'alt', widget: 'string', i18n: true }
              - { label: 'Caption', name: 'text', widget: 'markdown', required: false, i18n: true }
          - label: Intro text
            name: text
            widget: markdown
            required: false
            i18n: true
      - label: Topics
        label_singular: Topic
        name: list
        i18n: true
        create: true
        #sortable_fields: ['question']
        summary: "#{{object.anchor}} – {{object.question}}"
        widget: list
        fields:
          - label: Topic
            name: object
            i18n: true
            create: true
            widget: object
            fields:
              - label: Question
                name: question
                widget: string
                i18n: true
              - label: Answer
                name: answer
                widget: markdown
                i18n: true
              - label: Anchor
                name: anchor
                widget: string
                i18n: duplicate

  - label: News
    name: news
    folder: content/news
    create: true
    label_singular: Post
    #summary: "{{menutitle}}"
    identifier_field: menutitle
    i18n: true
    fields: 
    - label: Type
      name: type
      widget: hidden
      i18n: duplicate
      default: "news"
    - label: Title
      name: title
      widget: string
      i18n: true
    - label: Meta keywords
      name: keywords
      widget: string
      required: false
      i18n: true
    - label: Meta description
      name: description
      widget: string
      required: false
      i18n: true
    - label: Menutitle (short)
      name: menutitle
      widget: string
      i18n: true
    - label: Subtitle
      name: subtitle
      widget: string
      i18n: true
    - label: URL alias (slug)
      name: slug
      widget: string
      default: "{{menutitle}}"
      i18n: true
    - label: Publish date
      name: date
      widget: datetime
      i18n: duplicate
    - label: Body
      name: body
      widget: markdown
      i18n: true

  - name: ctas
    label: CTAs
    label_singular: CTA
    folder: content/ctas
    create: true
    i18n: true
    summary: "{{button}}"
    fields:
      - label: ID
        name: title
        widget: string
        i18n: duplicate
      - name: button
        label: Button text
        widget: string
        i18n: true
      - label: Link to
        name: link
        widget: string
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true
